### ISSUE TITLE
Exception on postgresql - bad Db column name

### ISSUE THREAD

**Issue by JimKerslake** [cloudscribe/pwakit#37]
An exception occurred while iterating over the results of a query for context type '"cloudscribe.PwaKit.Storage.EFCore.PostgreSql.PwaDbContext"'." ""Npgsql.PostgresException (0x80004005): 42703: column c.p256dh does not exist POSITION: 77 at Npgsql.Internal.NpgsqlConnector.g__ReadMessageLong|213_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage) at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken) at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken) at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken) at Npgsql.NpgsqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken) at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken) at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken) at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken) at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken) at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync() Exception data: Severity: ERROR SqlState: 42703 MessageText: column c.p256dh does not exist Hint: Perhaps you meant to reference the column \"c.p256_dh\". Position: 77 File: parse_relation.c Line: 3548 Routine: errorMissingColumn"

**Comment by JimKerslake** [comment]
Also fix another null ref excaption:

  An unhandled exception has occurred while executing the request.
System.NullReferenceException: Object reference not set to an instance of an object.
   at cloudscribe.PwaKit.Services.PushServicePushNotificationService.get_PublicKey() in D:\Development\pwakit\src\cloudscribe.PwaKit\Services\Push\PushNotificationService.cs:line 17
   at cloudscribe.PwaKit.Controllers.PwaController.GetPublicKey() in D:\Development\pwakit\src\cloudscribe.PwaKit\Controllers\PwaController.cs:line 131
   at lambda_method2333(Closure , Object , Object[] )

**Comment by JimKerslake** [comment]
Also added migration for a stray PgSQL timestamp column to make it 'with timezone'
